language: node_js
node_js:
- '11'
before_install: npm i -g grunt-cli
install: npm i

script:
- npm run lint
- npm run es-check

deploy:
  - provider: script
    script: bash scripts/minify.sh
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    on:
      branch: master

  - provider: npm
    email: fupduck@sacknagel.com
    api_key:
      secure: RVIkWmnHuOVfaDBTKWZCcJSt1kec9EGwps3Ax44oAM8OwbUPSLjOu3AeMqXxzdAofdAZHjrfehLoYxQkZANI0hds9SzdlJ2ANzwScW/WT8O4vuGYTaPhBG/4QhaY6N/Kt7DE0rWZ2SOxs4PE+0AJiI96Pzm5/L02HcG9DluhZpcKCQXfEfIVWP806Wur6dVxlZJzMlBTH0MVCqaCzenU75QY+5MTEjaVSGOmH0ab4wrJxN+hpMZGsfFZPhex9MaAI3ZYmtWt+0yBcVBOIRsNg4Ykth7WEjSNEZHxaKFC9EsuZLS7aSJBCRpxGvIXOzCqmWUnMCxajR5ovmc9uwBAOlXPE3F1wSycJMP004MzIPHza/PmVNfvg1uhIpI9BO/gDUl4rcL+6oAnmwex7cY+sCNC0hp87o4ZxvJSMplidiuphuD/2TrPQ5IDn6q+4wcfbZ2sRWofw4YMXakt0E0b1qVMlA8aNPJGUj0VZo2SfiAbzgWb04Ja/iqPQMKjWVw+pEwo8SUfZaEISgdrS0nxjsiuOo2Svymb0AXz3LCAAVEfNRQxQg1o+vVouRy7IUHCS/a3I2/Tk2Rwl4Yp5lAc6xGpvdfVRZPKergVDAMlqbqmwnoRAGu14pKzoWDXOr9m3QFO9TT7Bzkb3jIKsAq4RmYZuPnP0974whZufsq4kok=
    on:
      tags: true
      repo: dwilhelm89/Leaflet.StyleEditor

